# Generated by Django 3.1 on 2020-08-23 12:47

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='personal_others',
            field=django_mysql.models.ListTextField(models.IntegerField(), default='', size=None),
        ),
    ]
