# Generated by Django 3.1 on 2020-08-23 12:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person_personal_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personal_others',
            field=django_mysql.models.ListTextField(models.CharField(max_length=300), size=None),
        ),
    ]
