# Generated by Django 3.1 on 2020-08-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200823_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=25)),
                ('role', models.TextField()),
                ('where', models.TextField()),
            ],
        ),
    ]
