# Generated by Django 3.1 on 2020-08-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_education'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='WorkExperience',
        ),
    ]
