# Generated by Django 3.1 on 2020-08-23 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200823_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(default=datetime.datetime(2020, 8, 23, 14, 29, 51, 454762))),
                ('course', models.TextField()),
                ('school', models.TextField()),
            ],
        ),
    ]
