# Generated by Django 3.1 on 2020-08-23 14:37

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='date',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 14, 36, 48, 193138)),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 14, 36, 48, 192610)),
        ),
    ]
