# Generated by Django 3.1 on 2020-08-23 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200823_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('who', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('text', models.TextField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 16, 9, 19, 10592)),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 16, 9, 19, 10972)),
        ),
    ]
