# Generated by Django 3.1 on 2020-08-23 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200823_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 16, 10, 33, 439857)),
        ),
        migrations.AlterField(
            model_name='reference',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 16, 10, 33, 440245)),
        ),
    ]
