# Generated by Django 3.1 on 2020-08-23 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200823_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 16, 23, 51, 306679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 16, 23, 51, 307054, tzinfo=utc)),
        ),
    ]
